-- ============================================================================
-- Kneiphof, Phase 11: Tabellen mit dem Praefix KNH_ im Schema DEMO
-- Aufbau wie bei Heidelberg (HEI_) und Semiramis (SEM_): Praefix je Projekt, <TABELLE>_ID,
-- _PK / _FK / _CK je Tabelle. Jede Anweisung endet mit einer Zeile "/".
-- Das Skript kann mehrfach laufen: was es schon gibt, meldet der Einrichter als "vorhanden".
-- Reihenfolge: 01 Tabellen, 02 Folgen, Trigger, Indizes, 03 Paket KNH_API.
-- Zeichensatz: UTF-8.
-- ============================================================================

CREATE TABLE KNH_SESSION (
  SESSION_ID      NUMBER(10)     NOT NULL,
  GESTARTET       TIMESTAMP(6)   DEFAULT LOCALTIMESTAMP NOT NULL,
  BEENDET         TIMESTAMP(6),
  DAUER_S         NUMBER(8),
  RECHNER         VARCHAR2(80 CHAR),
  BENUTZER        VARCHAR2(60 CHAR),
  APP_VERSION     VARCHAR2(20 CHAR),
  JAVA_VERSION    VARCHAR2(40 CHAR),
  GRAFIK          VARCHAR2(120 CHAR),
  KERNE           NUMBER(3),
  SPEICHER_MAX_MB NUMBER(6),
  FENSTER_B       NUMBER(5),
  FENSTER_H       NUMBER(5),
  ZUSTAND_GELADEN CHAR(1)        DEFAULT 'N' NOT NULL,
  BILDER_S        NUMBER(5,1),
  MS_BILD         NUMBER(6,1),
  SPEICHER_MB     NUMBER(6),
  CONSTRAINT KNH_SESSION_PK PRIMARY KEY (SESSION_ID),
  CONSTRAINT KNH_SESSION_GELADEN_CK CHECK (ZUSTAND_GELADEN IN ('J','N'))
)
/

CREATE TABLE KNH_STATE (
  STATE_ID        NUMBER(10)     NOT NULL,
  NAME            VARCHAR2(60 CHAR)   NOT NULL,
  ART             VARCHAR2(8)    NOT NULL,
  GESPEICHERT     TIMESTAMP(6)   DEFAULT LOCALTIMESTAMP NOT NULL,
  SESSION_ID      NUMBER(10),
  TAG              NUMBER(3)    DEFAULT 172 NOT NULL,
  STUNDE           NUMBER(5,2)  DEFAULT 10.5 NOT NULL,
  ZEITRAFFER       NUMBER(1)    DEFAULT 0 NOT NULL,
  DUNST            NUMBER(3)    DEFAULT 30 NOT NULL,
  WIND             NUMBER(3)    DEFAULT 30 NOT NULL,
  NEBEL            NUMBER(1)    DEFAULT 0 NOT NULL,
  WETTER           NUMBER(1)    DEFAULT 0 NOT NULL,
  BELICHTUNG       NUMBER(3)    DEFAULT 0 NOT NULL,
  AUFLOESUNG       NUMBER(3)    DEFAULT 100 NOT NULL,
  AUFLOESUNG_AUTO  CHAR(1)      DEFAULT 'N' NOT NULL,
  SCHATTEN         CHAR(1)      DEFAULT 'J' NOT NULL,
  BLOOM            CHAR(1)      DEFAULT 'J' NOT NULL,
  FXAA             CHAR(1)      DEFAULT 'J' NOT NULL,
  SPIEGELUNG       CHAR(1)      DEFAULT 'J' NOT NULL,
  STRAHLEN         CHAR(1)      DEFAULT 'J' NOT NULL,
  FUSSGAENGER      CHAR(1)      DEFAULT 'J' NOT NULL,
  MOEWEN           CHAR(1)      DEFAULT 'J' NOT NULL,
  RAUCH            CHAR(1)      DEFAULT 'J' NOT NULL,
  BAEUME           CHAR(1)      DEFAULT 'J' NOT NULL,
  HAEUSER          CHAR(1)      DEFAULT 'J' NOT NULL,
  SCHIFFE          CHAR(1)      DEFAULT 'J' NOT NULL,
  PRUEFSTAND       CHAR(1)      DEFAULT 'N' NOT NULL,
  BETRIEB          CHAR(1)      DEFAULT 'N' NOT NULL,
  DREHPUNKT_X      NUMBER(10,2) DEFAULT -40 NOT NULL,
  DREHPUNKT_Y      NUMBER(10,2) DEFAULT 4 NOT NULL,
  DREHPUNKT_Z      NUMBER(10,2) DEFAULT 10 NOT NULL,
  GIER_GRAD        NUMBER(8,2)  DEFAULT 215 NOT NULL,
  NICK_GRAD        NUMBER(5,2)  DEFAULT 24 NOT NULL,
  ABSTAND_M        NUMBER(9,2)  DEFAULT 900 NOT NULL,
  CONSTRAINT KNH_STATE_PK PRIMARY KEY (STATE_ID),
  CONSTRAINT KNH_STATE_ART_CK CHECK (ART IN ('AUTO','MANUELL')),
  CONSTRAINT KNH_STATE_SESSION_FK FOREIGN KEY (SESSION_ID) REFERENCES KNH_SESSION (SESSION_ID) ON DELETE SET NULL,
  CONSTRAINT KNH_STATE_TAG_CK CHECK (TAG BETWEEN 1 AND 366),
  CONSTRAINT KNH_STATE_STUNDE_CK CHECK (STUNDE BETWEEN 0 AND 24),
  CONSTRAINT KNH_STATE_ZEITRAFFER_CK CHECK (ZEITRAFFER BETWEEN 0 AND 4),
  CONSTRAINT KNH_STATE_DUNST_CK CHECK (DUNST BETWEEN 0 AND 100),
  CONSTRAINT KNH_STATE_WIND_CK CHECK (WIND BETWEEN 0 AND 120),
  CONSTRAINT KNH_STATE_NEBEL_CK CHECK (NEBEL BETWEEN 0 AND 3),
  CONSTRAINT KNH_STATE_WETTER_CK CHECK (WETTER BETWEEN 0 AND 2),
  CONSTRAINT KNH_STATE_BELICHTUNG_CK CHECK (BELICHTUNG BETWEEN -20 AND 20),
  CONSTRAINT KNH_STATE_AUFLOESUNG_CK CHECK (AUFLOESUNG BETWEEN 50 AND 100),
  CONSTRAINT KNH_STATE_AUFLOESUNG_AUTO_CK CHECK (AUFLOESUNG_AUTO IN ('J','N')),
  CONSTRAINT KNH_STATE_SCHATTEN_CK CHECK (SCHATTEN IN ('J','N')),
  CONSTRAINT KNH_STATE_BLOOM_CK CHECK (BLOOM IN ('J','N')),
  CONSTRAINT KNH_STATE_FXAA_CK CHECK (FXAA IN ('J','N')),
  CONSTRAINT KNH_STATE_SPIEGELUNG_CK CHECK (SPIEGELUNG IN ('J','N')),
  CONSTRAINT KNH_STATE_STRAHLEN_CK CHECK (STRAHLEN IN ('J','N')),
  CONSTRAINT KNH_STATE_FUSSGAENGER_CK CHECK (FUSSGAENGER IN ('J','N')),
  CONSTRAINT KNH_STATE_MOEWEN_CK CHECK (MOEWEN IN ('J','N')),
  CONSTRAINT KNH_STATE_RAUCH_CK CHECK (RAUCH IN ('J','N')),
  CONSTRAINT KNH_STATE_BAEUME_CK CHECK (BAEUME IN ('J','N')),
  CONSTRAINT KNH_STATE_HAEUSER_CK CHECK (HAEUSER IN ('J','N')),
  CONSTRAINT KNH_STATE_SCHIFFE_CK CHECK (SCHIFFE IN ('J','N')),
  CONSTRAINT KNH_STATE_PRUEFSTAND_CK CHECK (PRUEFSTAND IN ('J','N')),
  CONSTRAINT KNH_STATE_BETRIEB_CK CHECK (BETRIEB IN ('J','N')),
  CONSTRAINT KNH_STATE_DREHPUNKT_X_CK CHECK (DREHPUNKT_X BETWEEN -1000000 AND 1000000),
  CONSTRAINT KNH_STATE_DREHPUNKT_Y_CK CHECK (DREHPUNKT_Y BETWEEN -10000 AND 100000),
  CONSTRAINT KNH_STATE_DREHPUNKT_Z_CK CHECK (DREHPUNKT_Z BETWEEN -1000000 AND 1000000),
  CONSTRAINT KNH_STATE_GIER_GRAD_CK CHECK (GIER_GRAD BETWEEN -10000 AND 10000),
  CONSTRAINT KNH_STATE_NICK_GRAD_CK CHECK (NICK_GRAD BETWEEN -90 AND 90),
  CONSTRAINT KNH_STATE_ABSTAND_M_CK CHECK (ABSTAND_M BETWEEN 0.1 AND 100000)
)
/

CREATE TABLE KNH_EVENT (
  EVENT_ID        NUMBER(10)     NOT NULL,
  SESSION_ID      NUMBER(10)     NOT NULL,
  ZEIT            TIMESTAMP(6)   DEFAULT LOCALTIMESTAMP NOT NULL,
  SEKUNDE         NUMBER(8,1)    NOT NULL,
  ART             VARCHAR2(12)   NOT NULL,
  ZIEL            VARCHAR2(80 CHAR),
  WERT            VARCHAR2(200 CHAR),
  TAG             NUMBER(3),
  STUNDE          NUMBER(5,2),
  CONSTRAINT KNH_EVENT_PK PRIMARY KEY (EVENT_ID),
  CONSTRAINT KNH_EVENT_SESSION_FK FOREIGN KEY (SESSION_ID) REFERENCES KNH_SESSION (SESSION_ID) ON DELETE CASCADE
)
/

-- Kommentare

COMMENT ON TABLE KNH_SESSION IS 'Eine Zeile je Programmstart: Rechner, Grafikkarte, Fenster, Dauer, Bilder pro Sekunde'
/

COMMENT ON TABLE KNH_STATE IS 'Zustand des Programms (Kamera, Zeit, Wetter, Schalter): AUTO beim Beenden und alle 60 Sekunden, MANUELL als benannte Ansicht'
/

COMMENT ON TABLE KNH_EVENT IS 'Protokoll einer Sitzung: Start, Ende, Fehler, Fahrten, Brücken, Fotos, Einrichter'
/
