-- ============================================================================
-- Kneiphof, Phase 11: Folgen, Trigger, Indizes
-- Folge <TABELLE>_SEQ und Trigger <TABELLE>_BI vergeben die ID, wie in deinen anderen Projekten.
-- ============================================================================

-- Folgen

CREATE SEQUENCE KNH_SESSION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE SEQUENCE KNH_STATE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE SEQUENCE KNH_EVENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

-- Trigger

CREATE OR REPLACE TRIGGER KNH_SESSION_BI
BEFORE INSERT ON KNH_SESSION
FOR EACH ROW
WHEN (NEW.SESSION_ID IS NULL)
BEGIN
  :NEW.SESSION_ID := KNH_SESSION_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER KNH_STATE_BI
BEFORE INSERT ON KNH_STATE
FOR EACH ROW
WHEN (NEW.STATE_ID IS NULL)
BEGIN
  :NEW.STATE_ID := KNH_STATE_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER KNH_EVENT_BI
BEFORE INSERT ON KNH_EVENT
FOR EACH ROW
WHEN (NEW.EVENT_ID IS NULL)
BEGIN
  :NEW.EVENT_ID := KNH_EVENT_SEQ.NEXTVAL;
END;
/

-- Indizes auf Fremdschluesseln und Abfragen

CREATE INDEX KNH_STATE_SESSION_IX ON KNH_STATE (SESSION_ID)
/

CREATE INDEX KNH_STATE_ART_IX ON KNH_STATE (ART, GESPEICHERT)
/

CREATE INDEX KNH_EVENT_SESSION_IX ON KNH_EVENT (SESSION_ID, ZEIT)
/

CREATE INDEX KNH_SESSION_START_IX ON KNH_SESSION (GESTARTET)
/
